### PR TITLE
#1477: Get rid of Future.failed in IOs

### LINKED ISSUE #1477: Refactor `ScioIO` instances to get rid of the `Future.failed` in writes and `Tap`
The idea being to return a successful `Future[Tap[Nothing]]` instead.

### PR DESCRIPTION
**Pull request by jto**
Fixes #1477

### CODE REVIEW

File: scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala [hunk 1]
```diff
@@ -24,6 +24,33 @@ import com.spotify.scio.values.SCollection
...
+  def saveForTest(data: SCollection[A])(implicit c: Coder[A]): Future[Tap[T]]
+}
+
+object TapT {
+  // scalastyle:off structural.type
+  type Aux[A, T0] = TapT[A] { type T = T0 }
+  // scalastyle:on structural.type
+}
+
+final class TapOfNothing[A] private extends TapT[A] {
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala]: @jto should we name this `EmptyTapOf[A]`

File: scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala [hunk 2]
```diff
@@ -24,6 +24,33 @@ import com.spotify.scio.values.SCollection
 
 import scala.concurrent.Future
 
+sealed trait TapT[A] {
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala]: @jto I think we could move this to `Tap.scala`?

File: scio-core/src/main/scala/com/spotify/scio/io/Tap.scala [hunk 3]
```diff
@@ -60,6 +60,11 @@ trait Tap[T] extends Serializable { self =>
 
 }
 
+final case object EmptyTap extends Tap[Nothing] {
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/io/Tap.scala]: @jto 🎨 i think `final` here is redundant, since it's a top level object

File: scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala (hunk 2 above)
Comment (jto) [reply scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala]: No. The only use of the class is to encode the fact the write and tap can either return a `Tap[A]` or a `Tap[Nothing]`. It's actually not strictly related to `Tap` but I can't find a better name...

Comment (regadas) [reply scio-core/src/main/scala/com/spotify/scio/io/ScioIO.scala]: yeah on a second thought I agree with you! 👍
