### PR TITLE
Fix #449. Warn on scala.App

### LINKED ISSUE #449: Using App trait causes java.lang.NullPointerException with Side Inputs
Extending the `App` trait in Scala and running a job from there produces a NullPointerException when using Side Inputs (I specifically testing with SingletonSideInputs)
### Example
```
object PubSubIngester extends App {
  @transient lazy val logger = Logger(LoggerFactory.getLogger(this.getClass.getCanonicalName))

  val (seidrOpts, cmdlineArgs) = ScioContext.parseArguments[SeidrOptions](args)
  val utils = new SeidrUtils(seidrOpts)

  val sc = ScioContext(seidrOpts)

  val sideInput: SideInput[String] =
      sc.parallelize(Option(seidrOpts.getArg)).asSingletonSideInput

  sc.pubsubSubscription(seidrOpts.getSubscription, timestampLabel = "timestamp")
    .withSideInputs(sideInput)
    .map((message, sideInputContext) => (message, sideInputContext(sideInput)))
    .toSCollection
    .map{ case (messageStr, sideStr) => logger.info(s"Message $messageStr, Side $sideStr") }

  val result = sc.close()
}
```

Produces:
> Exception: java.lang.NullPointerException
com.spotify.scio.values.SideInputContext.apply(SideInput.scala:82)
com.bigvikinggames.seidr.etl.google.PubSubIngester$$anonfun$collections$1$1$$anonfun$apply$1.apply(PubSubIngester.scala:92)
com.bigvikinggames.seidr.etl.google.PubSubIngester$$anonfun$collections$1$1$$anonfun$apply$1.apply(PubSubIngester.scala:92)
com.spotify.scio.util.FunctionsWithSideInput$$anon$3.processElement(FunctionsWithSideInput.scala:56)

### Workaround
Moving to using `main` instead of extending `App` works perfectly fine:
```
object PubSubIngester {
  def main(args: Array[String]): Unit = {
    @transient lazy val logger = Logger(LoggerFactory.getLogger(this.getClass.getCanonicalName))

    val (seidrOpts, cmdlineArgs) = ScioContext.parseArguments[SeidrOptions](args)
    val utils = new SeidrUtils(seidrOpts)

    val sc = ScioContext(seidrOpts)

    val sideInput: SideInput[String] =
      sc.parallelize(Option(seidrOpts.getArg)).asSingletonSideInput

    sc.pubsubSubscription(seidrOpts.getSubscription, timestampLabel = "timestamp")
      .withSideInputs(sideInput)
      .map((message, sideInputContext) => (message, sideInputContext(sideInput)))
      .toSCollection
      .map{ case (messageStr, sideStr) => logger.info(s"Message $messageStr, Side $sideStr") }

    val result = sc.close()
  }
}
```

Reproduced locally and on Dataflow. Note added to the FAQ by @ravwojdyla here: https://github.com/spotify/scio/wiki/FAQ#scalaapp-trait-vs-main-method

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

**Comment by ravwojdyla** [comment]
"Best" effort to warn users about `scala.App` also documented [here](https://github.com/spotify/scio/wiki/FAQ#scalaapp-trait-vs-main-method)

**Comment by andrewsmartin** [comment]
👍

File: scio-core/src/main/scala/com/spotify/scio/ScioContext.scala [hunk 1]
```diff
@@ -171,6 +171,16 @@ class ScioContext private[scio] (val options: PipelineOptions,
     o.setScioVersion(scioVersion)
   }
 
+  {
+    /** Check if running within [[scala.App]] see https://github.com/spotify/scio/issues/449 */
+    if (Thread.currentThread()
+      .getStackTrace.toList.map(_.getClassName.split('$').head)
+      .exists(_.equals(classOf[App].getName))) {
+      logger.warn(
+        "Applications declared within scala.App might not work properly, please use main method!")
```
Comment (nevillelyh) [inline scio-core/src/main/scala/com/spotify/scio/ScioContext.scala]: grammar nazi: "defined" instead of "declared" (which suggests no impl). ". Please"
