### PR TITLE
bypass nullable coder for ObjectFileIO, fix #2187

### LINKED ISSUE #2187: Issue enabling nullable Coder with Scio 0.7.4
During the Scio migration from `0.6.1` to `0.7.4` had to enable nullable Coder since the source avro record contained null values and the job was failing.

After enabling it using `sc.optionsAs[ScioOptions].setNullableCoders(true)` the job would successfully finish, but the produced output proto file will not be readable.

Here is the error message I got while trying to read the file:

```Exception in thread "main" com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:105)
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:609)
	at me.lyh.protobuf.generic.GenericReader.read(GenericReader.scala:55)
	at me.lyh.protobuf.generic.GenericReader.read(GenericReader.scala:24)
	at org.apache.avro.tool.ProtobufReader.toJson(ProtobufReader.scala:9)
	at org.apache.avro.tool.ProtoToJsonTool.run(ProtoToJsonTool.java:59)
	at org.apache.avro.tool.ProtoMain.run(ProtoMain.java:64)
	at org.apache.avro.tool.ProtoMain.main(ProtoMain.java:53)```

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

File: scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala [hunk 1]
```diff
@@ -168,23 +169,62 @@ class TapTest extends TapSpec {
...
+      sc.optionsAs[ScioOptions].setNullableCoders(true)
+      sc.parallelize(actual)
+        .saveAsProtobufFile(dir.getPath)
+    }
+    val expected = actual.toSet
     verifyTap(t, expected)
+
+    val sc = ScioContext()
+    sc.protobufFile[SimplePBV3](dir + "/*.avro") should containInAnyOrder(expected)
+    sc.close()
```
Comment (regadas) [inline scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala]:
```suggestion
    sc.run()
```

File: scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala [hunk 2]
```diff
@@ -168,23 +169,62 @@ class TapTest extends TapSpec {
...
+      _.parallelize(actual)
+        .saveAsProtobufFile(dir.getPath)
+    }
+    val expected = actual.toSet
+    verifyTap(t, expected)
+
+    val sc = ScioContext()
+    sc.optionsAs[ScioOptions].setNullableCoders(true)
+    sc.protobufFile[SimplePBV3](dir + "/*.avro") should containInAnyOrder(expected)
+    sc.close()
```
Comment (regadas) [inline scio-test/src/test/scala/com/spotify/scio/io/TapTest.scala]:
```suggestion
    sc.run()
```
