### PR TITLE
(fix)[avro] Use correct DatumWriter constructor

### LINKED ISSUE #5331: AvroCoder fails on nullable Decimal types w/ Avro 1.11.3
Given the following schema:

```json
{
    "type": "record",
    "name": "TestRecord",
    "fields": [
         {
           "name": "nullableDecimal",
           "type": [
             "null",
             {
                 "type": "bytes",
                 "logicalType": "decimal",
                 "precision": 4,
                 "scale": 2
             }
           ]
         }
    ]
}
```

Scio's default AvroCoder fails to encode records with non-null values, throwing the following error:

```
[info]   org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"bytes","logicalType":"decimal","precision":4,"scale":2}]: 1.00
[info]   at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:910)
[info]   at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:307)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:157)
[info]   at org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:108)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:234)
[info]   at org.apache.avro.specific.SpecificDatumWriter.writeRecord(SpecificDatumWriter.java:92)
[info]   at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:145)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:95)
[info]   at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:82)
[info]   at org.apache.beam.sdk.extensions.avro.coders.AvroCoder.encode(AvroCoder.java:428)
```

(It works on Avro 1.8.2.)

This seems like it might be an issue with Avro itself (when you step through with a debugger, the GenericDatumWriter doesn't have the right conversions registered for the class), but we could still provide a workaround for it in Scio's SpecificDatumFactory?

Full repro: https://github.com/spotify/scio/compare/repro-nullable-decimal-err?expand=1

### PR DESCRIPTION
**Pull request by RustedBones**
Use correct avro writer constructor that would load the generated model with conversions.

Setup CI to test scio-avro with latest version on main

Fix #5331

### CODE REVIEW

File: scio-avro/src/main/scala/com/spotify/scio/avro/AvroDatumFactory.scala [hunk 1]
```diff
@@ -64,15 +64,9 @@ private[scio] object GenericRecordDatumFactory extends AvroDatumFactory.GenericD
...
   import SpecificRecordDatumFactory._
-  private class ScioSpecificDatumReader extends SpecificDatumReader[T](recordType) {
-    override def findStringClass(schema: Schema): Class[_] = super.findStringClass(schema) match {
-      case cls if cls == classOf[CharSequence] => classOf[String]
-      case cls                                 => cls
-    }
-  }
 
   override def apply(writer: Schema): DatumWriter[T] = {
-    val datumWriter = new SpecificDatumWriter[T]()
```
Comment (RustedBones) [inline scio-avro/src/main/scala/com/spotify/scio/avro/AvroDatumFactory.scala:75]: This constructor uses `SpecificData.get()` instead of expected `SpecificData.getForClass(c)`

File: scio-avro/src/test/scala-avro-latest/com/spotify/scio/avro/AvroDatumFactoryTest.scala [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+  "SpecificRecordDatumFactory" should "load model with conversions" in {
+    val factory = new SpecificRecordDatumFactory(classOf[LogicalTypesTest])
+    val schema = LogicalTypesTest.getClassSchema
+
+    {
+      val writer = factory(schema)
+      val data = writer.asInstanceOf[SpecificDatumWriter[LogicalTypesTest]].getData
+      // top-level
+      val timestamp = data.getConversionFor(LogicalTypes.timestampMillis())
+      timestamp shouldBe a[TimeConversions.TimestampMillisConversion]
```
Comment (RustedBones) [inline scio-avro/src/test/scala-avro-latest/com/spotify/scio/avro/AvroDatumFactoryTest.scala:36]: this is incompatible with avro 1.8 (`TimeConversions.TimestampConversion`) hence the source split.

File: scio-avro/src/test/scala-avro-latest/com/spotify/scio/avro/AvroDatumFactoryTest.scala [hunk 3]
```diff
@@ -0,0 +1,65 @@
...
+
+  "SpecificRecordDatumFactory" should "load model with conversions" in {
+    val factory = new SpecificRecordDatumFactory(classOf[LogicalTypesTest])
+    val schema = LogicalTypesTest.getClassSchema
+
+    {
+      val writer = factory(schema)
+      val data = writer.asInstanceOf[SpecificDatumWriter[LogicalTypesTest]].getData
+      // top-level
+      val timestamp = data.getConversionFor(LogicalTypes.timestampMillis())
```
Comment (RustedBones) [inline scio-avro/src/test/scala-avro-latest/com/spotify/scio/avro/AvroDatumFactoryTest.scala:35]: This was returning null in avro 1.11.3 without the fix

File: build.sbt [hunk 4]
```diff
@@ -58,7 +58,7 @@ val googleApiServicesPubsubVersion = s"v1-rev20220904-$googleClientsVersion"
 val googleApiServicesStorageVersion = s"v1-rev20240311-$googleClientsVersion"
 // beam tested versions
 val zetasketchVersion = "0.1.0" // sdks/java/extensions/zetasketch/build.gradle
-val avroVersion = "1.8.2" // sdks/java/extensions/avro/build.gradle
+val avroVersion = avroCompilerVersion // sdks/java/extensions/avro/build.gradle
```
Comment (clairemcginty) [inline build.sbt:61]: where does `avroCompilerVersion` get declared? 👀

**Review by clairemcginty — APPROVED** [review]

File: build.sbt (hunk 4 above)
Comment (RustedBones) [reply build.sbt:61]: This is exposed by the [sbt-avro](https://github.com/sbt/sbt-avro) plugin. It makes sure we have the compiler and library version in sync
