### PR TITLE
Fix BigQuery implicit coder

### LINKED ISSUE #3606: Bigquery `TableRow` default coder
With the move to `scio-google-cloud-platform` the default coder for `TableRow` became the `GenericJson` coder. This coder differs from `TableRowCoder` (backed by Jackson ObjectMapper) slightly in value conversion. 

`JsonObjectParser` converts every (int, float, double) to `java.math.BigDecimal`. Users updating to 0.10.0 if casting values will face smth like:

```
org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.ClassCastException: java.math.BigDecimal cannot be cast to java.lang.Integer
```

1) We could introduce back `Coder[TableRow]`. Users migrating will need to:

```
import com.spotify.bigquery.coders._
```

**or**

2) we can change the `Coder[T <: GenericJson]` to use jackson `ObjectMapper` instead. This would make things smooth for those using this module but it would break things for those relying on this coder.

I think I'm going with option 1) since users will need to migrate to that new module which already introduces some other changes.

### PR DESCRIPTION
**Pull request by regadas**
fixes #3606

In a follow-up PR, I'll update the migration notes for the new `scio-google-platform` module. We need users to be aware that some of the coders are not resolved implicitly anymore due to the dependency decoupling.

### CODE REVIEW

File: scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/instances/CoderInstances.scala [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ */
+
+package com.spotify.scio.bigquery.instances
+
+import com.spotify.scio.coders.Coder
+import com.google.api.services.bigquery.model.TableRow
+import org.apache.beam.sdk.io.gcp.bigquery.TableRowJsonCoder
+
+trait CoderInstances {
+  implicit def tableRowCoder: Coder[TableRow] = Coder.beam(TableRowJsonCoder.of())
```
Comment (nevillelyh) [inline scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/instances/CoderInstances.scala:25]: Maybe be more source-compat if we make this available via `import com.spotify.scio.bigquery._`?

Comment (regadas) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/instances/CoderInstances.scala:25]: Hi @nevillelyh right, tbh I thought about it; I avoided that because it deviates a bit from the overall way to add coders; in most modules now (including this one) `Coder`'s are brought into scope through `import com.spotify.scio.<smth>.coders._`. 

Since we also set explicitly the coder for the `TableRow` based IO's should cover most of the cases. wdyt? should we still add it?

On a side note, I'm thinking of removing the `GenericJson` coder from scope. Json encode/decode tends to be different and specific to IO's.

Comment (nevillelyh) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/instances/CoderInstances.scala:25]: Yeah should probably be enough.
Maybe we can document all the available coders/artifacts/namespaces in a table?

Comment (regadas) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/instances/CoderInstances.scala:25]: That's a good idea!
