### PR TITLE
Julient/1665 better coder exceptions

### LINKED ISSUE #1665: Improve the stacktrace on Null exceptions in Coders
The new Coder impl does not support `null` values by default. While the behaviour is fine, when an exception happens, the stacktrace does not show you **where** the exception was thrown which makes it hard locate the code, and therefore, what should be a trivial fix becomes a really hard one.

Here's an example of a exception thrown in a pipeline while runnning tests. Note that the entire stack is beam ou scio internals, and it does not reference the pipeline code at all.

```
[info]   org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Exception while trying to `encode` field _2 with value null
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:332)
[info]   at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:302)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:197)
[info]   at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:64)
[info]   at org.apache.beam.sdk.Pipeline.run(Pipeline.java:313)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:350)
[info]   at org.apache.beam.sdk.testing.TestPipeline.run(TestPipeline.java:331)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:489)
[info]   at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:476)
[info]   at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:542)
[info]   at com.spotify.scio.ScioContext.close(ScioContext.scala:476)
[info]   at com.spotify.descriptors.lexicon.DescriptorLexiconJobTest$$anonfun$4.apply(DescriptorLexiconJobTest.scala:184)
[info]   at com.spotify.descriptors.lexicon.DescriptorLexiconJobTest$$anonfun$4.apply(DescriptorLexiconJobTest.scala:175)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FreeSpecLike$$anon$1.apply(FreeSpecLike.scala:407)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FreeSpec.withFixture(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike$class.invokeWithFixture$1(FreeSpecLike.scala:404)
[info]   at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:417)
[info]   at org.scalatest.FreeSpecLike$$anonfun$runTest$1.apply(FreeSpecLike.scala:417)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.FreeSpecLike$class.runTest(FreeSpecLike.scala:417)
[info]   at org.scalatest.FreeSpec.runTest(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:476)
[info]   at org.scalatest.FreeSpecLike$$anonfun$runTests$1.apply(FreeSpecLike.scala:476)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
[info]   at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
[info]   at scala.collection.immutable.List.foreach(List.scala:392)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.FreeSpecLike$class.runTests(FreeSpecLike.scala:476)
[info]   at org.scalatest.FreeSpec.runTests(FreeSpec.scala:1739)
[info]   at org.scalatest.Suite$class.run(Suite.scala:1147)
[info]   at org.scalatest.FreeSpec.org$scalatest$FreeSpecLike$$super$run(FreeSpec.scala:1739)
[info]   at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:520)
[info]   at org.scalatest.FreeSpecLike$$anonfun$run$1.apply(FreeSpecLike.scala:520)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.FreeSpecLike$class.run(FreeSpecLike.scala:520)
[info]   at org.scalatest.FreeSpec.run(FreeSpec.scala:1739)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:480)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[info]   at sbt.TestRunner.run(TestFramework.scala:124)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFunction.apply(TestFramework.scala:294)
[info]   at sbt.Tests$.$anonfun$toTask$1(Tests.scala:309)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:67)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:278)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: java.lang.RuntimeException: Exception while trying to `encode` field _2 with value null
[info]   at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:171)
[info]   at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:180)
[info]   at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:82)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:66)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:51)
[info]   at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:141)
[info]   at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:113)
[info]   at org.apache.beam.sdk.util.MutationDetectors.forValueWithCoder(MutationDetectors.java:44)
[info]   at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.add(ImmutabilityCheckingBundleFactory.java:112)
[info]   at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:260)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:172)
[info]   Cause: org.apache.beam.sdk.coders.CoderException: cannot encode a null String
[info]   at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:74)
[info]   at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:68)
[info]   at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:37)
[info]   at com.spotify.scio.coders.RecordCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:181)
[info]   at com.spotify.scio.coders.RecordCoder$$anonfun$encode$1.apply(Coder.scala:181)
[info]   at com.spotify.scio.coders.RecordCoder$$anonfun$encode$1.apply(Coder.scala:181)
[info]   at com.spotify.scio.coders.RecordCoder.onErrorMsg(Coder.scala:169)
[info]   at com.spotify.scio.coders.RecordCoder.encode(Coder.scala:180)
[info]   at org.apache.beam.sdk.coders.Coder.encode(Coder.java:136)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:82)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:66)
[info]   at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:51)
[info]   at org.apache.beam.sdk.util.CoderUtils.clone(CoderUtils.java:141)
[info]   at org.apache.beam.sdk.util.MutationDetectors$CodedValueMutationDetector.<init>(MutationDetectors.java:113)
[info]   at org.apache.beam.sdk.util.MutationDetectors.forValueWithCoder(MutationDetectors.java:44)
[info]   at org.apache.beam.runners.direct.ImmutabilityCheckingBundleFactory$ImmutabilityEnforcingBundle.add(ImmutabilityCheckingBundleFactory.java:112)
[info]   at org.apache.beam.runners.direct.ParDoEvaluator$BundleOutputManager.output(ParDoEvaluator.java:260)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
[info]   at com.spotify.scio.util.Functions$$anon$7.processElement(Functions.scala:172)
[info]   at com.spotify.scio.util.Functions$$anon$7$DoFnInvoker.invokeProcessElement(Unknown Source)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:275)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimpleDoFnRunner.processElement(SimpleDoFnRunner.java:240)
[info]   at org.apache.beam.repackaged.beam_runners_direct_java.runners.core.SimplePushbackSideInputDoFnRunner.processElementInReadyWindows(SimplePushbackSideInputDoFnRunner.java:78)
[info]   at org.apache.beam.runners.direct.ParDoEvaluator.processElement(ParDoEvaluator.java:207)
[info]   at org.apache.beam.runners.direct.DoFnLifecycleManagerRemovingTransformEvaluator.processElement(DoFnLifecycleManagerRemovingTransformEvaluator.java:54)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.processElements(DirectTransformExecutor.java:160)
[info]   at org.apache.beam.runners.direct.DirectTransformExecutor.run(DirectTransformExecutor.java:124)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info] ScalaTest
```

### PR DESCRIPTION
**Pull request by jto**
fixes #1665

### CODE REVIEW

File: scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala [hunk 1]
```diff
@@ -132,9 +132,39 @@ private final case class DisjunctionCoder[T, Id](typeName: String,
...
+   * to provide a helpful stacktrace if an exception happens
+   */
+  private val stackTrace: Array[StackTraceElement] =
+    Thread
+      .currentThread()
+      .getStackTrace()
+      .dropWhile(_.getClassName.contains(WrappedBCoder.getClass.getName))
+
+  private def buildException(cause: Throwable): Exception =
+    new RuntimeException {
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala]: @jto should we provide this as `CoderException` instead of just `RuntimeException`?

File: scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala [hunk 2]
```diff
@@ -35,8 +35,8 @@ object CoderMaterializer {
     coder match {
       case Beam(c) =>
         val nullableCoder = o.as(classOf[com.spotify.scio.options.ScioOptions]).getNullableCoders()
-        if (nullableCoder) NullableCoder.of(c)
-        else c
+        if (nullableCoder) WrappedBCoder.create(NullableCoder.of(c))
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala]: @jto nice catch here! I found that KvCoder is not wrapped as well.  Maybe we can make this like 
```scala
  final def beam[T](r: CoderRegistry, o: PipelineOptions, coder: Coder[T]): BCoder[T] =
    WrappedBCoder.create {
         ...
    }
```
