### PR TITLE
Use ## and support consistent Array hashCode

### LINKED ISSUE #2450: Non primitive keys result in incorrect sparse transforms for more than 125M sparse keys
For cases when the smaller side of the sparse transforms have more than 125M keys, we partition the data and use multiple BloomFilters. This partitioning logic relies on Java's `.hashCode()` on the Key of the Pair SCollection.

Java's `.hashCode()` is non deterministic (in its API) and returns non primitive types (arrays and tuples).

Hence sparse do not work for arrays and tuples + more than 125M keys.

It is fairly easy for the user to make this mistake :(

### PR DESCRIPTION
**Pull request by regadas**
Closes #2450

### CODE REVIEW

File: scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala [hunk 1]
```diff
@@ -173,20 +174,21 @@ class PairSCollectionFunctions[K, V](val self: SCollection[(K, V)]) {
...
    */
-  def hashPartitionByKey(numPartitions: Int): Seq[SCollection[(K, V)]] =
-    self.partition(
-      numPartitions,
-      {
-        case (key, _) =>
-          Math.floorMod(key.hashCode(), numPartitions)
-      }
-    )
+
```
Comment (nevillelyh) [inline scio-core/src/main/scala/com/spotify/scio/values/PairSCollectionFunctions.scala:184]:
```suggestion
```
