### PR TITLE
Mock BQ wildcard table

### LINKED ISSUE #3248: Enable partitioned table for mockTable
I am aggregating some events for 7 days from a partitioned table(https://ghe.spotify.net/ads/adserver-data-pipelines/blob/base_ctr/adserver-data-pipelines/src/main/scala/com/spotify/ads/adserver/pipelines/batch/bidadjustment/CreativeBaseCTRJob.scala), and want to use mockTable(https://ghe.spotify.net/ads/adserver-data-pipelines/blob/644014c0f3f06c6ebf37c2f7544c037c5c54fdc3/adserver-data-pipelines/src/test/scala/com/spotify/ads/adserver/pipelines/batch/bidadjustment/CreativeBaseCTRJobTest.scala#L133) for integration tests of my SQL.

I got this error for table not found. I guess this is because my original table is partitioned. 
`
com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "Not found: Table ad-selfserve:ad_platform_services.clean_flights",
    "reason" : "notFound"
  } ],
  "message" : "Not found: Table ad-selfserve:ad_platform_services.clean_flights",
  "status" : "NOT_FOUND"
}
`

### PR DESCRIPTION
**Pull request by RustedBones**
Fix #3248 

Adding `mockWildcardTable` API on `MockBigQuery` 

Eg: To get the highest recorded temperature from the 2020s decade 

```sql
SELECT
  max,
  year,
  mo,
  da,
FROM
  `bigquery-public-data.noaa_gsod.gsod202*`
WHERE
  max != 9999.9 # code for missing data
  AND _TABLE_SUFFIX BETWEEN '0' AND '9'
ORDER BY
  max DESC
LIMIT 1
```

We can mock `bigquery-public-data.noaa_gsod.gsod2022` and use it as only matched table by the query with 

```
mockWildcardTable("bigquery-public-data.noaa_gsod.gsod202", "2").withData(...)
```

### CODE REVIEW

File: scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala [hunk 1]
```diff
@@ -64,6 +64,32 @@ class MockBigQuery private (private val bq: BigQuery) {
     new MockTable(bq, t.getSchema, original, temp)
   }
 
+  /**
+   * Mock a BigQuery wildcard table using the table prefix and the suffix matched by the wildcard.
+   * Each table can be mocked only once in a test class.
```
[the remark this answers is not in the document]
Comment (RustedBones) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala:69]: It is hard to separate the prefix from the suffix in the API since we need to check if the original table exists.
I kept the same API with `def mockWildcardTable(prefix: String, suffix: String)` but it is now possible to call it several times.

Moreover, having `withData(suffix1, data1)` will force to create a table on the fly, and doesn't allign well with the original API. We should have had smth like `mockTableData(original, data)` directly on `MockBigQuery` to be aligned.

We could imagine smth like `mockWildcard(prefix).mockTable(suffix1).withData(data1)` but I feel this indirection isn't helping

File: scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala [hunk 2]
```diff
@@ -70,23 +70,29 @@ class MockBigQuery private (private val bq: BigQuery) {
...
     )
 
-    val t = bq.tables.table(original)
-    val temp = bq.tables.createTemporary(t.getLocation, Some(suffix)).getTableReference
-    val tmpWildcard = new TableReference()
-      .setProjectId(temp.getProjectId)
-      .setDatasetId(temp.getDatasetId)
-      .setTableId(temp.getTableId.dropRight(suffix.length) + "*")
-    mapping += (wildcard -> tmpWildcard)
+    val ref = tempWildcard.clone().setTableId(tempWildcard.getTableId.dropRight(1) + suffix)
```
Comment (clairemcginty) [inline scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala:93]: maybe I'm missing something, how is `ref` different from `original`?

File: scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala [hunk 3]
```diff
@@ -93,16 +92,33 @@ class BigQueryIT extends AnyFlatSpec with Matchers {
...
+      )
     )
 
     val mbq = MockBigQuery()
-    mbq.mockWildcardTable(prefix, suffix).withData(inData)
-    mbq.queryResult(wildcardSqlQuery) should contain only inData.head
+    suffixData.foreach { case (suffix, inData) =>
+      mbq.mockWildcardTable(prefix, suffix).withData(inData)
+    }
+    mbq.queryResult(wildcardSqlQuery) should contain only suffixData("21").head
```
Comment (clairemcginty) [inline scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala:121]: I thought BigQuery `BETWEEN` was inclusive, shouldn't the query also contain `suffixData("20")`?

**Review by clairemcginty — COMMENTED** [review]
this API looks good! just have a few questions

File: scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala (hunk 3 above)
Comment (RustedBones) [reply scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala:121]: the query retrieves the max temperature of the decade (`LIMIT 1`)
The highest one in the test data is in 2021, 1st element

File: scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala (hunk 2 above)
Comment (RustedBones) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala:93]: ref is actually pointing to the test table in the staging dataset:
- prefix: `bigquery-public-data.noaa_gsod.gsod20`
- suffix: `20`
- original: `bigquery-public-data.noaa_gsod.gsod2020`
- wildcard: `bigquery-public-data.noaa_gsod.gsod20*`
- tempWildcard: `my-test-project.scio_bigquery_staging_us_east_1.scio_query_20210422164412_*`
- ref:  `my-test-project.scio_bigquery_staging_us_east_1.scio_query_20210422164412_20`

Comment (RustedBones) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala:93]: could also be named `temp` since we do not have to get the reference after creation

File: scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala (hunk 3 above)
Comment (kellen) [reply scio-google-cloud-platform/src/it/scala/com/spotify/scio/bigquery/BigQueryIT.scala:121]: Seems like removing `LIMIT 1` would provide a better test?

File: scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala (hunk 1 above)
[the remark this answers is not in the document]
Comment (kellen) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala:69]: IMO simplicity is a benefit here, so keeping a single `mockWildcardTable` call, analogous to the existing `mockTable`, is better than adding complexity. Most users will likely have a map of suffix -> data anyway, so they'll just be `foreach`ing over it.

**Review by kellen — APPROVED** [review]

File: scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala (hunk 2 above)
Comment (clairemcginty) [reply scio-google-cloud-platform/src/main/scala/com/spotify/scio/bigquery/MockBigQuery.scala:93]: ah gotcha! Maybe rename to `tempRef`? 🎨  Otherwise looks good!

**Review by clairemcginty — APPROVED** [review]
