### PR TITLE
AvroType macro shouldn't generate duplicate record classes fix #2264)

### LINKED ISSUE #2264: Avro regenerates referenced definitions
In Scio 0.7.4, `@AvroType.fromSchema` regenerates case classes for previously seen definitions instead of reusing them, which breaks types which have multiple members of the same type.

```scala
@AvroType.fromSchema(
  """
  |{
  |  "type" : "record",
  |  "name" : "A",
  |  "fields" : [ {
  |    "name" : "a",
  |    "type" : {
  |      "type" : "record",
  |      "name" : "B",
  |      "fields" : [ ]
  |    }
  |  }, {
  |    "name" : "b",
  |    "type" : "B"
  |  } ]
  |}""".stripMargin
)
class ReuseDef
```

This example fails with:
```
ReuseDef$B is already defined as case class ReuseDef$B
```

`avro-tool idl2schemata` will generate this case from this IDL input:

```
protocol test {
  record B {}

  record A {
    B a;
    B b;
  }
}
```

### PR DESCRIPTION
**Pull request by ClaireMcGinty**
fix #2264

### CODE REVIEW

File: scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala [hunk 1]
```diff
@@ -279,7 +279,16 @@ private[types] object TypeProvider {
...
       val f = schema.getFields.asScala
         .map(f => extractField(className, f.name, f.schema))
-      (f.map(_._1), f.flatMap(_._2))
+
+      val fields = f.map(_._1)
+
+      val recordClasses = f
+        .flatMap(_._2)
+        .groupBy(_.asInstanceOf[ClassDef].name)
+        .map { case (_, cDefs) => cDefs.head } // Don't generate duplicate case classes
```
Comment (ClaireMcGinty) [inline scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala]: note that if there are conflicting definitions of a nested record type, the Avro schema parser itself will catch it before getting to this step.

Comment (nevillelyh) [inline scio-avro/src/main/scala/com/spotify/scio/avro/types/TypeProvider.scala]:
```suggestion
        // note that if there are conflicting definitions of a nested record type, the Avro schema
        // parser itself will catch it before getting to this step.
        .map { case (_, cDefs) => cDefs.head } // Don't generate duplicate case classes
```
