### PR TITLE
fix #1831, Avro map string key cast exception

### LINKED ISSUE #1831: typed Avro map causes cast error
Reading a typed Avro file with a map field triggers the following exception:
```
[error] Caused by: com.spotify.scio.coders.CoderException: org.apache.avro.util.Utf8 cannot be cast to java.lang.String
[error]         at org.apache.beam.sdk.coders.StringUtf8Coder.encode(StringUtf8Coder.java:37)
[error]         at com.spotify.scio.coders.instances.MapCoder.encode(ScalaCoders.scala:248)   
[error]         at com.spotify.scio.coders.instances.MapCoder.encode(ScalaCoders.scala:240)
[error]         at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply$mcV$sp(Coder.scala:195)
[error]         at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:195)
[error]         at com.spotify.scio.coders.WrappedBCoder$$anonfun$encode$1.apply(Coder.scala:195)
[error]         at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:189)
[error]         at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:195)
[error]         at com.spotify.scio.coders.instances.OptionCoder$$anonfun$encode$6.apply(ScalaCoders.scala:165)
[error]         at com.spotify.scio.coders.instances.OptionCoder$$anonfun$encode$6.apply(ScalaCoders.scala:165)
[error]         at scala.Option.foreach(Option.scala:274)
[error]         at com.spotify.scio.coders.instances.OptionCoder.encode(ScalaCoders.scala:165)
[error]         at com.spotify.scio.coders.instances.OptionCoder.encode(ScalaCoders.scala:161)

```

Job generating Avro file
```scala
  @AvroType.toSchema
  case class A(i: Int, m: Option[Map[String, Float]])

  def main(args: Array[String]): Unit = {
    val (sc, _) = ContextAndArgs(args)
    sc.parallelize(Seq(A(1, Some(Map("a" -> 1.0f)))))
      .saveAsTypedAvroFile("x")
   sc.close()
  }
```

Job reading it back
```scala
  def main(args: Array[String]): Unit = {
    val (sc, _) = ContextAndArgs(args)
   sc.typedAvroFile[A]("x/*.avro").debug()
    sc.close()
  }
```

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

File: scio-avro/src/test/scala/com/spotify/scio/avro/types/ConverterProviderTest.scala [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+package com.spotify.scio.avro.types
+
+import java.nio.file.Files
+
+import com.spotify.scio._
+import com.spotify.scio.avro._
+import org.apache.commons.io.FileUtils
+import org.scalatest._
+
+class ConverterProviderTest extends FlatSpec with Matchers with BeforeAndAfterAll {
```
Comment (regadas) [inline scio-avro/src/test/scala/com/spotify/scio/avro/types/ConverterProviderTest.scala]:
```suggestion
class ConverterProviderTest extends FlatSpec with Matchers {
```
