### PR TITLE
#1651: Fix Magnolia generated tree annotations removal

### LINKED ISSUE #1651: Derived Coders are sometimes non serializable
Happens because `removeAnnotations` does not actually remove all annotations. See Spotify's internal slack/so for an example.

### PR DESCRIPTION
**Pull request by jto**
fixes #1651

### CODE REVIEW

File: scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala [hunk 1]
```diff
@@ -147,16 +147,22 @@ private[coders] object CoderMacros {
...
+              super.transform(t2)
+            case q"""new magnolia.SealedTrait($typeName, $subtypes, $annotations)""" =>
+              val t2 = q"""new _root_.magnolia.SealedTrait($typeName, $subtypes, Array())"""
+              super.transform(t2)
+            case q"""magnolia.Magnolia.subtype[$tc, $t, $p]($typeName, $id, $annotations, $coder, $cast0, $cast1)""" =>
+              val t2 =
+                q"""_root_.magnolia.Magnolia.subtype[$tc, $t, $p]($typeName, $id, Array(), $coder, $cast0, $cast1)"""
+              super.transform(t2)
             case t =>
               super.transform(tree)
```
Comment (regadas) [inline scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala]: @jto 🎨 this can be `super.transform(t)` right?

File: scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala [hunk 2]
```diff
@@ -147,16 +147,22 @@ private[coders] object CoderMacros {
...
           tree match {
-            case Apply(AppliedTypeTree(Select(pack, TypeName("CaseClass")), ps),
-                       List(typeName, isObject, isValueClass, params, annotations)) =>
-              Apply(AppliedTypeTree(Select(pack, TypeName("CaseClass")), ps),
-                    List(typeName, isObject, isValueClass, params, q"""Array()"""))
-            case q"""new magnolia.CaseClass[$tc, $t]($typeName, $isObject, $isValueClass, $params, $annotations){ $body }""" =>
-              q"""_root_.magnolia.CaseClass[$tc, $t]($typeName, $isObject, $isValueClass, $params, Array()){ $body }"""
-            case q"com.spotify.scio.coders.Coder.dispatch(new magnolia.SealedTrait($name, $subtypes, $annotations))" =>
-              q"_root_.com.spotify.scio.coders.Coder.dispatch(new magnolia.SealedTrait($name, $subtypes, Array()))"
+            case t @ Apply(AppliedTypeTree(Select(pack, TypeName("CaseClass")), ps),
```
Comment (regadas) [inline scio-macros/src/main/scala/com/spotify/scio/coders/CoderMacros.scala]: @jto `t @` doesn't seem to be needed?

**Comment by jto** [comment]
@regadas Fixed according to your comments :)
