### PR TITLE
Fixes #550. Human friendly job/app names for REPL jobs.

### LINKED ISSUE #550: JobName when launching from REPL is obfuscated
https://console.cloud.google.com/dataflow/job/2017-04-17_09_21_03-283097507720515786?project=scio-playground

`appName` is `sciorepl` but `jobName` is `iw0-neville-0417161943-905c9e5f`, possibly internal Scala class from stacktrace.

### PR DESCRIPTION
**Pull request by ravwojdyla**

### CODE REVIEW

File: scio-repl/src/main/scala/com/spotify/scio/repl/ReplScioContext.scala [hunk 1]
```diff
@@ -24,6 +24,10 @@ class ReplScioContext(options: PipelineOptions,
                       artifacts: List[String])
   extends ScioContext(options, artifacts) {
 
+  private val scioReplName = "sciorepl"
+  this.setAppName(scioReplName)
+  this.setJobName(scioReplName)
```
Comment (ravwojdyla) [inline scio-repl/src/main/scala/com/spotify/scio/repl/ReplScioContext.scala]: Actually I should include username there + some hash to get around limit of 1 jobname at a time.
