### PR TITLE
Make recursive coders serializable

### LINKED ISSUE #2269: SCollection of recursive types produces NotSerializableException
I'm new to this project, so please bear with me.

I have a `SCollection` with a type referring to a recursive type, it produces this exception when I `flatMap` over it

```
Caused by: java.io.NotSerializableException: PipelineOptions objects are not serializable and should not be embedded into transforms (did you capture a PipelineOptions object in a field or in an anonymous class?). Instead, if you're using a DoFn, access PipelineOptions at runtime via ProcessContext/StartBundleContext/FinishBundleContext.getPipelineOptions(), or pre-extract necessary fields from PipelineOptions at pipeline construction time.
        at org.apache.beam.sdk.options.ProxyInvocationHandler.writeObject(ProxyInvocationHandler.java:176)
```

I reproduced the error in the test for derivation of recursive encoders, please see the linked PR.

This is the problematic path, if it's not obvious to you:

* `com.spotify.scio.values.PCollectionWrapper.parDo` materializes the coder, [link](https://github.com/spotify/scio/blob/master/scio-core/src/main/scala/com/spotify/scio/values/PCollectionWrapper.scala#L58). This gives a `com.spotify.scio.coders.WrappedBCoder`.
* [`CoderTranslation.toProto`](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/CoderTranslation.java#L82) does not recognize `WrappedBCoder` and to triggers serialization through [`toCustomCoder`](https://github.com/apache/beam/blob/master/runners/core-construction-java/src/main/java/org/apache/beam/runners/core/construction/CoderTranslation.java#L113)

Please note that this path is not caused by the recursive type, but the recursive types fails to serialize with the error above.

### PR DESCRIPTION
**Pull request by jto**
(partially) Fixes #2269
The coder derivation still needs to happen in a "safe" location bc. Magnolia generates a `lazy val`

### CODE REVIEW

File: scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala [hunk 1]
```diff
@@ -170,21 +170,45 @@ private final case class DisjunctionCoder[T, Id](
...
     } else {
       c.structuralValue(value)
     }
+  }
+
+  override def hashCode(): Int = check {
+    typeName.hashCode + (41 * c.hashCode())
+  }
+
+  override def equals(obj: Any): Boolean = check {
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala]: we could make `RefCoder` `case class` and keep it short?

File: scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala [hunk 2]
```diff
@@ -87,7 +88,11 @@ object CoderMaterializer {
         refs
           .get(t)
           .getOrElse {
-            lazy val bc: BCoder[T] = beamImpl(r, o, c, refs + (t -> RefCoder(t, bc)))
+            // #2269: _REALLY_ support recursive ADTs
+            val bc = RefCoder[T](t, null) // placeholder
+            refs.put(t, bc)
+            val actualImpl = beamImpl(r, o, c, refs)
+            bc.setImpl(actualImpl)
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala]: couldn't we just do?

```
bc.c = beamImpl(r, o, c, refs)
```

File: scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala [hunk 3]
```diff
@@ -170,21 +170,45 @@ private final case class DisjunctionCoder[T, Id](
     }
 }
 
-private[scio] final class RefCoder[T](val typeName: String, c: => BCoder[T]) extends BCoder[T] {
+private[scio] final class RefCoder[T](val typeName: String, var c: BCoder[T]) extends BCoder[T] {
   def value: BCoder[T] = c
```
Comment (regadas) [inline scio-core/src/main/scala/com/spotify/scio/coders/Coder.scala]: since it's a `var` now we could remove this and probably have a better name for `c`?

**Comment by jto** [comment]
@regadas updated :)

File: scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala (hunk 2 above)
Comment (regadas) [reply scio-core/src/main/scala/com/spotify/scio/coders/CoderMaterializer.scala]: @jto you’re in favor of keeping setImpl?
