### PR TITLE
Fix #726 ProjectId nonEmpty string check in BigQueryClient

### LINKED ISSUE #726: Throw exception if the Project Id isn't valid passed to BigQueryClient.apply
I wasted some time today because I passed an empty string to the BigQueryClient.apply method. An exception was only thrown when I call BigQueryClient.query and the exception was a NullPointerException. It would be a better developer experience if BigQueryClient.apply threw an exception if the project id wasn't valid.

### PR DESCRIPTION
**Pull request by guidj**
To fail on client creation, rather than later, if the projectId is either null or an empty
string. Fixes #726

### CODE REVIEW

File: scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala [hunk 1]
```diff
@@ -74,6 +74,9 @@ private[scio] trait QueryJob {
 class BigQueryClient private (private val projectId: String,
                               _credentials: Credentials = null) { self =>
 
+  require(projectId != null && projectId.nonEmpty, "Invalid `projectId`. " +
```
Comment (ravwojdyla) [inline scio-bigquery/src/main/scala/com/spotify/scio/bigquery/BigQueryClient.scala]: Probably no need to \` the `projectId`.

File: scio-bigquery/src/test/scala/com/spotify/scio/bigquery/BigQueryClientTest.scala [hunk 2]
```diff
@@ -0,0 +1,46 @@
...
+    assertThrows[IllegalArgumentException] {
+      BigQueryClient("")
+    }
+
+    assertThrows[IllegalArgumentException] {
+      BigQueryClient(null)
+    }
+  }
+
+  "BigQueryClient" should "work with non-empty ProjectId" in {
```
Comment (ravwojdyla) [inline scio-bigquery/src/test/scala/com/spotify/scio/bigquery/BigQueryClientTest.scala]: Use `it` - it's more idiomatic.
