### PR TITLE
fix #1303, meaningful NPE message for nulls in BigQuery macro

### LINKED ISSUE #1303: BigQueryType.fromTableRow throws NPE without explanation for nullable fields without an Option
When converting from a TableRow to a case class and if the TableRow is missing a field that isn't an Option type, fromTableRow will throw an NPE without any explanation. The Following shows the problem:

```
class MissingFieldTest extends PipelineSpec {

  case class Artist(artist: String, artist2: String)

  "FromJSon should work" should "work" in {
    val goodJson =
      """
        |{
        |    "artist" : "spotify:artist",
        |    "artist2" : "spotify:artist2"
        |}
      """.stripMargin

    val badJson =
      """
        |{
        |    "artist" : "spotify:artist"
        |}
      """.stripMargin

    val goodtr = new JacksonFactory().fromString(goodJson, classOf[TableRow])
    val goodartist: Artist = BigQueryType.fromTableRow[Artist](goodtr)

    val badtr = new JacksonFactory().fromString(badJson, classOf[TableRow])
    val artist: Artist = BigQueryType.fromTableRow[Artist](badtr)
  }
}
```

Gives an exception like:
```
java.lang.NullPointerException
    at com.spotify.MissingVectorTest$$anonfun$1$$anonfun$3.apply(MissingFieldTest.scala:36)
    at com.spotify.MissingVectorTest$$anonfun$1$$anonfun$3.apply(MissingFieldTest.scala:36)
    at com.spotify.MissingVectorTest$$anonfun$1.apply$mcV$sp(MissingFieldTest.scala:36)
    at com.spotify.MissingVectorTest$$anonfun$1.apply(MissingFieldTest.scala:16)
    at com.spotify.MissingVectorTest$$anonfun$1.apply(MissingFieldTest.scala:16)
    ....
```

An error message beyond an NPE would be nice, since it is kinda hard to figure out what is going on.

### PR DESCRIPTION
**Pull request by nevillelyh**

### CODE REVIEW

**Comment by nevillelyh** [comment]
Did a micro benchmark

```scala
@BenchmarkMode(Array(Mode.AverageTime))
@OutputTimeUnit(TimeUnit.NANOSECONDS)
@State(Scope.Thread)
class BQBenchmark {

  val tr = TableRow("a" -> "hello")

  import BQBenchmark._
  @Benchmark def fromTableRow = Record.fromTableRow(tr)
}

object BQBenchmark {
  @BigQueryType.toTable
  case class Record(a: String)
}
```

Before the change:
```
[info] Benchmark                 Mode  Cnt   Score   Error  Units
[info] BQBenchmark.fromTableRow  avgt   30  84.408 ± 2.075  ns/op
```

After the change:
```
[info] Benchmark                 Mode  Cnt   Score    Error  Units
[info] BQBenchmark.fromTableRow  avgt   30  82.580 ± 0.936  ns/op
```

Don't think it'll affect performance much.

File: scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+import org.scalatest._
+
+class ConverterProviderTest extends FlatSpec with Matchers {
+
+  import ConverterProviderTest._
+
+  // scalastyle:off no.whitespace.before.left.bracket
+  "ConverterProvider" should "throw NPE with meaningful message for null in REQUIRED field" in {
+    the [NullPointerException] thrownBy {
+      Required.fromTableRow(TableRow())
```
Comment (anne-decusatis) [inline scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala]: I didn't realize you could construct table rows this way in tests! Thanks for the example :)

Comment (nevillelyh) [reply scio-bigquery/src/test/scala/com/spotify/scio/bigquery/types/ConverterProviderTest.scala]: It's a syntactic suger in `com.spotify.scio.bigquery`.
https://github.com/spotify/scio/blob/master/scio-bigquery/src/main/scala/com/spotify/scio/bigquery/package.scala#L102
